sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ARWoaLQf6nI7KtOhvqGI89l10D2YsBBsKZeHWZEQOFG67/K7cb+ZXy/21qr3dWPU2v30f/b7pbzZE6POHNXKzTsOUFDI9Nr0Oj2PKKVh1UqBUjeExyO/d61tyMx8uoybw9cAlGf64UdiVhYwktIx5v5wybIjoHXqR4I9guYnJfxWkt7h6zyE9l9vLY53b4mNwzXYnHeyebvjyFohJsxpabwAdugUldCWntJ66eBj58EwuPXJLkb8cJDadVxVOt/Tqhel0kweX5bqgWHNsxEIfzyA+apQk1LtHxAH4vgbe/S3B7cYhBIRXCXF1JUw10+KdhovBwDdGarCi6CCFNKKzl8x+bKhPtqnx6Gr95NKvTnFdj0anj2anPw2f8keqhZX81cZWUXmBMnGoX06rMrxYBxGQum0CP8kDIIMfxoFfPRDeXFHIEwIA2xP2xuWeVfZac4SB2X0ec2/r7Bj8tDyzPmwf8pVFh8GRssVOOEAXkQExVqqZ5Uv0PUU77aY9AENrcrRti2uumdr5CT+eLuSR2jsM5mLgfWaV029weiBc9n/bbQGZtyG+j1qm7W09WHX03pJsdfdp98kPZfieSfnyBfYTaUpC7o7Dvk9eUPU/Kw4wGr4f29LfwK1kqpCTiIXgalJVybDNdcsxHlkHze5ws4oU8vSvqoFv+6/qKtPfzw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/State-of-the-Union-Addresses_5048
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy